export { default as Home } from './Home'
export { default as Drive } from './Drive'
export { default as Results } from './Results' 
export { default as Analyze } from './Analyze' 
export { default as Tester } from './Tester' 